[[IOAPI]]
arch = "aarch64"
git-tree-sha1 = "143228e4408607ac01b24532b0a117e2dd70cc16"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "f50fc0a9edd45f3daeceff045023abe41ba0effbb75e16218d26954b42ad2727"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[IOAPI]]
arch = "aarch64"
git-tree-sha1 = "0201a4cfbff5476a6b8db20cd9f8fd614c0962a5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "d737bf70bd3b69b7dca8e8005c05d9dc52d9058ebb5a75f9312fd8166db266a5"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[IOAPI]]
arch = "aarch64"
git-tree-sha1 = "325588db5d70544defbda254d9c6933489fdbc00"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "b3d8dcbcfa94545f9093f1cc83a2a4078f31b5b19435c420f0c4294d848549e2"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "94fc624d52edb918ea1307bfc8003cb700cbbe0f"
libgfortran_version = "3.0.0"
os = "macos"

    [[IOAPI.download]]
    sha256 = "c2bf9d676918ae03968e0907db5d325ff3d047765026d2cd07a9eaaca4758fa5"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "447cda650237bcd6dc15f72e591637fb976422a3"
libgfortran_version = "4.0.0"
os = "macos"

    [[IOAPI.download]]
    sha256 = "91cc12d04ec978a6c3dc6550c0210072a6cf6c9b623ac235c8af3326317e6ec9"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "1eb135f1b698b562b4a148d136fa0a8e89d4a47d"
libgfortran_version = "5.0.0"
os = "macos"

    [[IOAPI.download]]
    sha256 = "2a9e9ae106016fdd722954e03f424a2c1897dc0862a243968542673da66a1d69"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "f4d726d35018f8ec5864f72dfadde9131dbf01b4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "8a9010356fccb0728c1f3c3d7abd2c0876aa4296a683c877e3a011b92177cbeb"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "0961f661ade4c9e9aa2dd27caa3dfc68adcf9c34"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "7cef09d6e179bf47403a6d2e6b8cf74f031aaa965a299a43b3e563214dd6e1b6"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "4d81af4daff3aa0e97bc1ffce9359f081a03aff6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "7c3659e8e4d140bf4ecdb146a5b3d9b665f68a226b2a695fbc75feba1ef4077b"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.0+1/IOAPI.v3.2.0.x86_64-linux-gnu-libgfortran5.tar.gz"
