[[IOAPI]]
arch = "aarch64"
git-tree-sha1 = "9cb7a4c0f802fa0dfd62e4f858834ed7d225f11d"
libgfortran_version = "5.0.0"
os = "macos"

    [[IOAPI.download]]
    sha256 = "5c495ee042f714418ccb2e4e25f9b293eb72d3dc16a3b754c0506c2fc5afd76d"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[IOAPI]]
arch = "aarch64"
git-tree-sha1 = "6504d4caf5d5e33d7b98a34311ed5f8bb6c81501"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "f8a2f15add600b49aa4dcf86212af3772c370041a5fbe9118829a66eb1e9fdd9"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[IOAPI]]
arch = "aarch64"
git-tree-sha1 = "5e618c5ca047244bddedf610bb6f8eeeb0f05f88"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "1d92a6ddd688bffd0d2b3423bbbd4a8488654cd078008562bdb942f135ff4779"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[IOAPI]]
arch = "aarch64"
git-tree-sha1 = "d6465f40d55d1810979453a9d6b53231197f4506"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "0ebbd29b1ee2408953e2d526c623989e9748bf4bb4470d2f8b14d3d9f4e30864"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "b1513cdf4b77af3d1d30266c28df0d64d06cc329"
libgfortran_version = "3.0.0"
os = "macos"

    [[IOAPI.download]]
    sha256 = "6444f63e3aa35c3e3deaa3de036725c09af8fc1d2a7ce3a87a873b3624f60d34"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "8d492060ef1b399bbd5145e094d512abdd9118e4"
libgfortran_version = "4.0.0"
os = "macos"

    [[IOAPI.download]]
    sha256 = "dcc70ceb76c9d6cb1421d2669c6970e5d79f38f62eaf0698ce99444d63cdc34e"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "5b861116068f83adfbf84ba8c4e71714c32fff69"
libgfortran_version = "5.0.0"
os = "macos"

    [[IOAPI.download]]
    sha256 = "533f5f1ef0859f90600773ab40d80ccb0a3f873529935e3fc32c0de17bd4e4f4"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "9cf6272ef68bdbefe5f499d3517824768b298dce"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "401a541273e162df372bb5077c70887bd7fea15759c2935a182d5bc0c00b85b3"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "41e2f2da3e73364df80553a9b6f86ea3c207d101"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "b7ef21d8a02ac78f9542633a1f1ae48bc0a5311f47b2d4ad3b551ce55678bdf8"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[IOAPI]]
arch = "x86_64"
git-tree-sha1 = "d660a303ab349ebb05f919dfdbee2193cacde716"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[IOAPI.download]]
    sha256 = "2de78bf3588741ce7084bcbfba6e64728741d3f0451dec2da8ca0eb4323cc3c1"
    url = "https://github.com/JuliaBinaryWrappers/IOAPI_jll.jl/releases/download/IOAPI-v3.2.1+0/IOAPI.v3.2.1.x86_64-linux-gnu-libgfortran5.tar.gz"
