# Autogenerated wrapper script for IOAPI_jll for x86_64-linux-gnu-libgfortran4
export airs2m3, bcwndw, camxtom3, datshift, dayagg, factor, findwndw, greg2jul, gregdate, gridprobe, insertgrid, jul2greg, juldate, juldiff, julshift, kfxtract, latlon, libioapi, m3agmask, m3agmax, m3combo, m3cple, m3diff, m3edhdr, m3fake, m3hdr, m3interp, m3mask, m3merge, m3pair, m3probe, m3stat, m3totxt, m3tproc, m3tshift, m3wndw, m3xtract, mpasdiff, mpasstat, mpastom3, mtxblend, mtxbuild, mtxcalc, mtxcple, presterp, presz, projtool, randomstat, selmrg2d, timediff, timeshift, vertimeproc, vertintegral, vertot, wndwdesc, wrfgriddesc, wrftom3

using NetCDF_jll
using NetCDFF_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("IOAPI")
JLLWrappers.@declare_executable_product(airs2m3)
JLLWrappers.@declare_executable_product(bcwndw)
JLLWrappers.@declare_executable_product(camxtom3)
JLLWrappers.@declare_executable_product(datshift)
JLLWrappers.@declare_executable_product(dayagg)
JLLWrappers.@declare_executable_product(factor)
JLLWrappers.@declare_executable_product(findwndw)
JLLWrappers.@declare_executable_product(greg2jul)
JLLWrappers.@declare_executable_product(gregdate)
JLLWrappers.@declare_executable_product(gridprobe)
JLLWrappers.@declare_executable_product(insertgrid)
JLLWrappers.@declare_executable_product(jul2greg)
JLLWrappers.@declare_executable_product(juldate)
JLLWrappers.@declare_executable_product(juldiff)
JLLWrappers.@declare_executable_product(julshift)
JLLWrappers.@declare_executable_product(kfxtract)
JLLWrappers.@declare_executable_product(latlon)
JLLWrappers.@declare_library_product(libioapi, "libioapi.so")
JLLWrappers.@declare_executable_product(m3agmask)
JLLWrappers.@declare_executable_product(m3agmax)
JLLWrappers.@declare_executable_product(m3combo)
JLLWrappers.@declare_executable_product(m3cple)
JLLWrappers.@declare_executable_product(m3diff)
JLLWrappers.@declare_executable_product(m3edhdr)
JLLWrappers.@declare_executable_product(m3fake)
JLLWrappers.@declare_executable_product(m3hdr)
JLLWrappers.@declare_executable_product(m3interp)
JLLWrappers.@declare_executable_product(m3mask)
JLLWrappers.@declare_executable_product(m3merge)
JLLWrappers.@declare_executable_product(m3pair)
JLLWrappers.@declare_executable_product(m3probe)
JLLWrappers.@declare_executable_product(m3stat)
JLLWrappers.@declare_executable_product(m3totxt)
JLLWrappers.@declare_executable_product(m3tproc)
JLLWrappers.@declare_executable_product(m3tshift)
JLLWrappers.@declare_executable_product(m3wndw)
JLLWrappers.@declare_executable_product(m3xtract)
JLLWrappers.@declare_executable_product(mpasdiff)
JLLWrappers.@declare_executable_product(mpasstat)
JLLWrappers.@declare_executable_product(mpastom3)
JLLWrappers.@declare_executable_product(mtxblend)
JLLWrappers.@declare_executable_product(mtxbuild)
JLLWrappers.@declare_executable_product(mtxcalc)
JLLWrappers.@declare_executable_product(mtxcple)
JLLWrappers.@declare_executable_product(presterp)
JLLWrappers.@declare_executable_product(presz)
JLLWrappers.@declare_executable_product(projtool)
JLLWrappers.@declare_executable_product(randomstat)
JLLWrappers.@declare_executable_product(selmrg2d)
JLLWrappers.@declare_executable_product(timediff)
JLLWrappers.@declare_executable_product(timeshift)
JLLWrappers.@declare_executable_product(vertimeproc)
JLLWrappers.@declare_executable_product(vertintegral)
JLLWrappers.@declare_executable_product(vertot)
JLLWrappers.@declare_executable_product(wndwdesc)
JLLWrappers.@declare_executable_product(wrfgriddesc)
JLLWrappers.@declare_executable_product(wrftom3)
function __init__()
    JLLWrappers.@generate_init_header(NetCDF_jll, NetCDFF_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        airs2m3,
        "bin/airs2m3",
    )

    JLLWrappers.@init_executable_product(
        bcwndw,
        "bin/bcwndw",
    )

    JLLWrappers.@init_executable_product(
        camxtom3,
        "bin/camxtom3",
    )

    JLLWrappers.@init_executable_product(
        datshift,
        "bin/datshift",
    )

    JLLWrappers.@init_executable_product(
        dayagg,
        "bin/dayagg",
    )

    JLLWrappers.@init_executable_product(
        factor,
        "bin/factor",
    )

    JLLWrappers.@init_executable_product(
        findwndw,
        "bin/findwndw",
    )

    JLLWrappers.@init_executable_product(
        greg2jul,
        "bin/greg2jul",
    )

    JLLWrappers.@init_executable_product(
        gregdate,
        "bin/gregdate",
    )

    JLLWrappers.@init_executable_product(
        gridprobe,
        "bin/gridprobe",
    )

    JLLWrappers.@init_executable_product(
        insertgrid,
        "bin/insertgrid",
    )

    JLLWrappers.@init_executable_product(
        jul2greg,
        "bin/jul2greg",
    )

    JLLWrappers.@init_executable_product(
        juldate,
        "bin/juldate",
    )

    JLLWrappers.@init_executable_product(
        juldiff,
        "bin/juldiff",
    )

    JLLWrappers.@init_executable_product(
        julshift,
        "bin/julshift",
    )

    JLLWrappers.@init_executable_product(
        kfxtract,
        "bin/kfxtract",
    )

    JLLWrappers.@init_executable_product(
        latlon,
        "bin/latlon",
    )

    JLLWrappers.@init_library_product(
        libioapi,
        "lib/libioapi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        m3agmask,
        "bin/m3agmask",
    )

    JLLWrappers.@init_executable_product(
        m3agmax,
        "bin/m3agmax",
    )

    JLLWrappers.@init_executable_product(
        m3combo,
        "bin/m3combo",
    )

    JLLWrappers.@init_executable_product(
        m3cple,
        "bin/m3cple",
    )

    JLLWrappers.@init_executable_product(
        m3diff,
        "bin/m3diff",
    )

    JLLWrappers.@init_executable_product(
        m3edhdr,
        "bin/m3edhdr",
    )

    JLLWrappers.@init_executable_product(
        m3fake,
        "bin/m3fake",
    )

    JLLWrappers.@init_executable_product(
        m3hdr,
        "bin/m3hdr",
    )

    JLLWrappers.@init_executable_product(
        m3interp,
        "bin/m3interp",
    )

    JLLWrappers.@init_executable_product(
        m3mask,
        "bin/m3mask",
    )

    JLLWrappers.@init_executable_product(
        m3merge,
        "bin/m3merge",
    )

    JLLWrappers.@init_executable_product(
        m3pair,
        "bin/m3pair",
    )

    JLLWrappers.@init_executable_product(
        m3probe,
        "bin/m3probe",
    )

    JLLWrappers.@init_executable_product(
        m3stat,
        "bin/m3stat",
    )

    JLLWrappers.@init_executable_product(
        m3totxt,
        "bin/m3totxt",
    )

    JLLWrappers.@init_executable_product(
        m3tproc,
        "bin/m3tproc",
    )

    JLLWrappers.@init_executable_product(
        m3tshift,
        "bin/m3tshift",
    )

    JLLWrappers.@init_executable_product(
        m3wndw,
        "bin/m3wndw",
    )

    JLLWrappers.@init_executable_product(
        m3xtract,
        "bin/m3xtract",
    )

    JLLWrappers.@init_executable_product(
        mpasdiff,
        "bin/mpasdiff",
    )

    JLLWrappers.@init_executable_product(
        mpasstat,
        "bin/mpasstat",
    )

    JLLWrappers.@init_executable_product(
        mpastom3,
        "bin/mpastom3",
    )

    JLLWrappers.@init_executable_product(
        mtxblend,
        "bin/mtxblend",
    )

    JLLWrappers.@init_executable_product(
        mtxbuild,
        "bin/mtxbuild",
    )

    JLLWrappers.@init_executable_product(
        mtxcalc,
        "bin/mtxcalc",
    )

    JLLWrappers.@init_executable_product(
        mtxcple,
        "bin/mtxcple",
    )

    JLLWrappers.@init_executable_product(
        presterp,
        "bin/presterp",
    )

    JLLWrappers.@init_executable_product(
        presz,
        "bin/presz",
    )

    JLLWrappers.@init_executable_product(
        projtool,
        "bin/projtool",
    )

    JLLWrappers.@init_executable_product(
        randomstat,
        "bin/randomstat",
    )

    JLLWrappers.@init_executable_product(
        selmrg2d,
        "bin/selmrg2d",
    )

    JLLWrappers.@init_executable_product(
        timediff,
        "bin/timediff",
    )

    JLLWrappers.@init_executable_product(
        timeshift,
        "bin/timeshift",
    )

    JLLWrappers.@init_executable_product(
        vertimeproc,
        "bin/vertimeproc",
    )

    JLLWrappers.@init_executable_product(
        vertintegral,
        "bin/vertintegral",
    )

    JLLWrappers.@init_executable_product(
        vertot,
        "bin/vertot",
    )

    JLLWrappers.@init_executable_product(
        wndwdesc,
        "bin/wndwdesc",
    )

    JLLWrappers.@init_executable_product(
        wrfgriddesc,
        "bin/wrfgriddesc",
    )

    JLLWrappers.@init_executable_product(
        wrftom3,
        "bin/wrftom3",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
